config/routes.rb
# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html
RedmineApp::Application.routes.draw do
    resources :announcements, only: [:new, :create, :edit, :update, :destroy]
end
get 'announcements_all', to: "announcements#announcement_data"
  

app/models/announcement.rb
class Announcement < ActiveRecord::Base
end

app/controllers/announcements_controller.rb
class AnnouncementsController < ApplicationController
  before_action :require_admin, except: [:announcement_data]
  def new
    @announcement = Announcement.new
  end
  def create
    @announcement = Announcement.new(announcement_params)
    if @announcement.save
      flash[:notice] = 'Announcement was successfully created.'
      redirect_to url_for(controller: '/my', action: :page)
    else
      render :new
    end
  end
  def edit
    @announcement = Announcement.find(params[:id])
  end

  def update
    @announcement = Announcement.find(params[:id])
    if @announcement.update(announcement_params)
      flash[:notice] = 'Announcement was successfully updated.'
      redirect_to url_for(controller: '/my', action: :page)
    else
      render :edit
    end
  end

  def destroy
    @announcement = Announcement.find(params[:id])
    @announcement.destroy
    flash[:notice] = 'Announcement was successfully updated.'
    redirect_to url_for(controller: '/my', action: :page)
  end
  def announcement_data
    puts 'raj'
    announcements=Announcement.where(announcement_date: Date.today)
    render json: announcements
  end
  private
  def announcement_params
    params.require(:announcement).permit(:title, :description, :announcement_date)
  end
end

app/views/announcements/_announcement.html.erb
<h2>Hello WOrld</h2>

app/views/announcements/_form.html.erb
<%= form_for(@announcement, url: { action: @announcement.new_record? ? "create" : "update", id: @announcement.id },html: {class: "announcement-form"}) do |f| %>
  <% if @announcement.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@announcement.errors.count, "error") %> prohibited this announcement from being saved:</h2>
      <ul>
      <% @announcement.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :"Announcement Title :" %><br>
    <%= f.text_field :title,class:"form-control",required: true%>
  </div>

  <div class="form-group">
    <%= f.label :"Announcement Description :" %><br>
    <%= f.text_area :description,class:"form-control",required: true%>
  </div>

    <div class="form-group">
      <%= f.label :"Announcement Date :" %>
      <%= f.date_field :announcement_date,class:"form-control"%>
    </div><br>
    <%= f.submit @announcement.new_record? ? 'Create' : 'Update'%>
<% end %>

<% content_for :header_tags do %>
    <%= stylesheet_link_tag 'bootstrap.min', plugin: 'redmineflux_announcement' %>
    <%= stylesheet_link_tag 'style', plugin: 'redmineflux_announcement' %>
<% end %>

app/views/announcements/edit.html.erb
<div class="form-div">
<h2 class="text-center">Edit Announcement</h2>
<%= render 'form', announcement: @announcement %>
<%= link_to 'Back', {controller: '/my', action: :page},class:"float-right btn btn-warning text-white"%>
</div>
<% content_for :header_tags do %>
    <%= stylesheet_link_tag 'bootstrap.min', plugin: 'redmineflux_announcement' %>
    <%= stylesheet_link_tag 'style', plugin: 'redmineflux_announcement' %>
<% end %>

app/views/announcements/new.html.erb
<div class="form-div">
<h2 class="text-center">New Announcement</h2>
<%= render 'form', announcement: @announcement %>
<%= link_to 'Back', {controller: '/my', action: :page},class:"float-right btn btn-warning text-white"%>
</div>
<% content_for :header_tags do %>
    <%= stylesheet_link_tag 'bootstrap.min', plugin: 'redmineflux_announcement' %>
    <%= stylesheet_link_tag 'style', plugin: 'redmineflux_announcement' %>
<% end %>

app/views/my/blocks/_announcements.erb
<div id="announcements">
    <% if !Announcement.where('announcement_date = ?', Date.today).present? %>
        <h2 class="announcemet_text mb-4">No Announcements Today</h2>
    <% else %>
        <h2 class="announcemet_text mb-4">Announcement</h2>
    <% end %>
  <% Announcement.where('announcement_date = ?', Date.today).each do |announcement| %>
    <div class="announcement">
      <h3 class="announcement-title"><%= announcement.title %></h3>
      <p class="announcement-text"><%= announcement.description %></p>
      <% if User.current.admin? %>
        <%= link_to 'Edit', edit_announcement_path(announcement), class: 'icon icon-edit edit-announcement' %>
        <%= link_to 'Delete', announcement_path(announcement), method: :delete, data: { confirm: 'Are you sure?' }, class: 'icon icon-del edit-announcement' %>
      <% end %>
    </div>
    <hr>
  <% end %>
  <% if User.current.admin? %>
  <%= link_to 'Create Announcement',new_announcement_path, class: 'icon icon-add'%>
<% end %>
</div>

<% content_for :header_tags do %>
    <%= stylesheet_link_tag 'main-page', plugin: 'redmineflux_announcement' %>
<% end %>
<%= javascript_include_tag 'index', plugin: 'redmineflux_announcement' %>